### ISSUE TITLE
`optimal_statistic.OptimalStatistic.compute_os` does not work with `MarginalizingTimingModel`

### ISSUE THREAD

**Issue by meyers-academic** [nanograv/enterprise_extensions#176]
We (@Hazboun6 and I) are seeing errors when trying to run the optimal statistic with a  `MarginalizingTimingModel`.  @AaronDJohnson pointed out that the matrices one gets out after marginalizing are different with the new, "faster" likelihood, and could change the OS implementation. Minimum working example below (although you need to supply your own pulsars and chains...)

```
import utils as my_utils
from enterprise_extensions.frequentist import optimal_statistic as opt_stat
from enterprise_extensions import models


psrs, noisedict = my_utils.load_15yr_v1p1_data_alt()
pta = models.model_2a(psrs, psd='powerlaw',
                      noisedict=noisedict, white_vary=False,
                      n_rnfreqs=30, n_gwbfreqs=14,
                      gamma_common=13./3.,
                      delta_common=None, upper_limit=False,
                      bayesephem=False,
                      be_type='setIII', is_wideband=False,
                      use_dmdata=False, select='backend',
                      tnequad=False,
                      pshift=False, pseed=None, psr_models=False,
                      tm_marg=True, dense_like=False, tm_svd=True)
newpars = {pta.param_names[ii]: pta.params[ii].sample() for ii in range(len(pta.param_names))}
ostat = opt_stat.OptimalStatistic(psrs, noisedict=noisedict, bayesephem=False, pta=pta)
xi, rho, sig, OS, SNR = ostat.compute_os(params=newpars)
```

This returns an error.
```
Traceback (most recent call last):
  File "/Users/patrickmeyers/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Volumes/bridges2.psc.edu – SFTP/15_year_runs/15_year_time_slices/mwe.py", line 20, in <module>
    xi, rho, sig, OS, SNR = ostat.compute_os(params=newpars)
  File "/Users/patrickmeyers/opt/anaconda3/envs/enterprise_code_review/lib/python3.9/site-packages/enterprise_extensions/frequentist/optimal_statistic.py", line 120, in compute_os
    FNTs = self.get_FNT(params=params)
  File "/Users/patrickmeyers/opt/anaconda3/envs/enterprise_code_review/lib/python3.9/site-packages/enterprise/signals/signal_base.py", line 1040, in wrapper
    cache[key] = func(self, params)
  File "/Users/patrickmeyers/opt/anaconda3/envs/enterprise_code_review/lib/python3.9/site-packages/enterprise_extensions/frequentist/optimal_statistic.py", line 437, in get_FNT
    FNTs.append(N.solve(T, left_array=F))
  File "/Users/patrickmeyers/opt/anaconda3/envs/enterprise_code_review/lib/python3.9/site-packages/enterprise/signals/gp_signals.py", line 877, in solve
    raise ValueError("Incorrect arguments given to MarginalizingNmat.solve.")
ValueError: Incorrect arguments given to MarginalizingNmat.solve.
```

**Comment by meyers-academic** [comment]
The solution here seems to be that you should *not* set `tm_marg=True` when constructing the PTA. I think we should probably add a check in the OS code to make sure that if someone uses a `MarginalizingTimingModel` then we return a sensible error.

**Comment by vallis** [comment]
Merged.
