### ISSUE TITLE
Issue with common process free spectrum

### ISSUE THREAD

**Issue by tsmith2** [nanograv/enterprise_extensions#94]
When running model 2a with a free spectrum for the common process I am getting the following error:

`UserWarning: No parameter prior match found between ['gw_log10_rho_0' 'gw_log10_rho_1' 'gw_log10_rho_2' 'gw_log10_rho_3'
 'gw_log10_rho_4' 'gw_log10_rho_5' 'gw_log10_rho_6' 'gw_log10_rho_7'
 'gw_log10_rho_8' 'gw_log10_rho_9' 'gw_log10_rho_10' 'gw_log10_rho_11'
 'gw_log10_rho_12' 'gw_log10_rho_13' 'gw_log10_rho_14' 'gw_log10_rho_15'
 'gw_log10_rho_16' 'gw_log10_rho_17' 'gw_log10_rho_18' 'gw_log10_rho_19'
 'gw_log10_rho_20' 'gw_log10_rho_21' 'gw_log10_rho_22' 'gw_log10_rho_23'
 'gw_log10_rho_24' 'gw_log10_rho_25' 'gw_log10_rho_26' 'gw_log10_rho_27'
 'gw_log10_rho_28' 'gw_log10_rho_29'] and PTA.object. `

From what I can tell the free spectrum priors are being set in the common_red_noise block, so it is unclear to me what might be causing this error.

**Comment by stevertaylor** [comment]
Hi @tsmith2. Could you give more details associated with your PTA setup?

**Comment by stevertaylor** [comment]
Very interesting. I'm a bit unsure what's the culprit here. Have you tried `model_general` with `orf=crn` to try the same thing?

**Comment by tsmith2** [comment]
Yes! When I run a free spectrum cnr using `model general` it works.

**Comment by tsmith2** [comment]
I may be using an older version of enterprise extensions, but in order to add a common red noise block I need to leave `orf=None`.... when I use the `model_general` I get the same error as before.

**Comment by tsmith2** [comment]
In case this is useful, there is the Traceback:

```
Traceback (most recent call last):
  File "gwb_anal.py", line 94, in <module>
    sampler = super_model.setup_sampler(resume=False, outdir=outDir, sample_nmodel=False)
  File "/home/physics/anaconda3/envs/enterprise/lib/python3.6/site-packages/enterprise_extensions/hypermodel.py", line 275, in setup_sampler
    par_names=[p for p in self.param_names if 'gw' in p]), 10)
  File "/home/physics/anaconda3/envs/enterprise/lib/python3.6/site-packages/enterprise_extensions/sampler.py", line 475, in draw_from_par_prior
    .format(par_names))
```
